<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AtlasOps.Connectors.Contracts\AtlasOps.Connectors.Contracts.csproj" />
    <ProjectReference Include="..\AtlasOps.Connectors.Runtime\AtlasOps.Connectors.Runtime.csproj" />
  </ItemGroup>
</Project>
