<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Modular\Modules\Automation\AtlasOps.Modules.Automation.Contracts\AtlasOps.Modules.Automation.Contracts.csproj" />
    <ProjectReference Include="..\..\..\src\Modular\Modules\Automation\AtlasOps.Modules.Automation.Core\AtlasOps.Modules.Automation.Core.csproj" />
    <ProjectReference Include="..\..\..\src\Modular\Platform\AtlasOps.Application\AtlasOps.Application.csproj" />
  </ItemGroup>
</Project>