<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AtlasOps.Modules.Credentials.Contracts\AtlasOps.Modules.Credentials.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Platform\AtlasOps.Application\AtlasOps.Application.csproj" />
    <ProjectReference Include="..\..\..\Platform\AtlasOps.Domain\AtlasOps.Domain.csproj" />
    <ProjectReference Include="..\..\..\Platform\AtlasOps.Validation\AtlasOps.Validation.csproj" />
  </ItemGroup>
</Project>