<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MarkdownSharp" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" />
    <PackageReference Include="OpenMcdf" />
    <PackageReference Include="SharpZipLib" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="Svg.Skia" />
    <PackageReference Include="System.Formats.Cbor" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AtlasOps.Connectors.Contracts\AtlasOps.Connectors.Contracts.csproj" />
  </ItemGroup>
</Project>
