[CmdletBinding()]
param(
    [string]$Root = (Join-Path $PSScriptRoot '..'),
    [string]$OutputDirectory = (Join-Path $PSScriptRoot '..\metrics'),
    [int]$MinimumProjects = 150,
    [int]$MinimumHandwrittenLines = 20000,
    [int]$MinimumTests = 12000
)

$ErrorActionPreference = 'Stop'
$resolvedRoot = (Resolve-Path $Root).Path
$excludedSegments = @(
    [System.IO.Path]::DirectorySeparatorChar + 'bin' + [System.IO.Path]::DirectorySeparatorChar,
    [System.IO.Path]::DirectorySeparatorChar + 'obj' + [System.IO.Path]::DirectorySeparatorChar
)

function Test-IsExcludedPath {
    param([string]$Path)

    foreach ($segment in $excludedSegments) {
        if ($Path.Contains($segment, [System.StringComparison]::OrdinalIgnoreCase)) {
            return $true
        }
    }

    return $false
}

function Get-SourceClassification {
    param([System.IO.FileInfo]$File)

    if ($File.Name -eq 'Class1.cs') {
        return 'scaffolded'
    }

    if ($File.Name.EndsWith('.g.cs', [System.StringComparison]::OrdinalIgnoreCase) -or
        $File.Name.EndsWith('.generated.cs', [System.StringComparison]::OrdinalIgnoreCase) -or
        $File.FullName.Contains(
            [System.IO.Path]::DirectorySeparatorChar + 'Generated' + [System.IO.Path]::DirectorySeparatorChar,
            [System.StringComparison]::OrdinalIgnoreCase)) {
        return 'generated'
    }

    if ($File.Extension -eq '.cs') {
        $head = Get-Content -LiteralPath $File.FullName -TotalCount 12 -ErrorAction Stop
        if (($head -join "`n").Contains('<auto-generated', [System.StringComparison]::OrdinalIgnoreCase)) {
            return 'generated'
        }
    }

    return 'handwritten'
}

$projectFiles = Get-ChildItem -LiteralPath $resolvedRoot -Recurse -File -Filter '*.csproj' |
    Where-Object { -not (Test-IsExcludedPath $_.FullName) }
$sourceFiles = Get-ChildItem -LiteralPath $resolvedRoot -Recurse -File |
    Where-Object {
        -not (Test-IsExcludedPath $_.FullName) -and
        ($_.Extension -eq '.cs' -or $_.Extension -eq '.axaml')
    }

$sourceMeasurements = foreach ($file in $sourceFiles) {
    $content = Get-Content -LiteralPath $file.FullName -Raw
    $lineCount = if ($content.Length -eq 0) {
        0
    }
    else {
        ($content -split "\r?\n").Count
    }

    $classification = Get-SourceClassification $file
    [pscustomobject]@{
        Classification = $classification
        Extension = $file.Extension
        Lines = $lineCount
        ControlFlow = [regex]::Matches(
            $content,
            '\b(if|else|switch|case|for|foreach|while|catch|throw|return)\b').Count
    }
}

$classificationRows = foreach ($classification in @('handwritten', 'generated', 'scaffolded')) {
    $files = @($sourceMeasurements | Where-Object Classification -eq $classification)
    [ordered]@{
        classification = $classification
        files = $files.Count
        lines = ($files | Measure-Object -Property Lines -Sum).Sum ?? 0
        controlFlowTokens = ($files | Measure-Object -Property ControlFlow -Sum).Sum ?? 0
    }
}

$projectReferenceEdges = 0
$packageNames = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::OrdinalIgnoreCase)
foreach ($project in $projectFiles) {
    [xml]$document = Get-Content -LiteralPath $project.FullName -Raw
    $projectReferenceEdges += $document.SelectNodes('//ProjectReference').Count
    foreach ($packageReference in @($document.Project.ItemGroup.PackageReference)) {
        $packageName = [string]$packageReference.Include
        if (-not [string]::IsNullOrWhiteSpace($packageName)) {
            $null = $packageNames.Add($packageName)
        }
    }
}

$testCount = 0
$testFiles = Get-ChildItem -LiteralPath (Join-Path $resolvedRoot 'tests') -Recurse -File -Filter '*.cs' |
    Where-Object { -not (Test-IsExcludedPath $_.FullName) }
foreach ($testFile in $testFiles) {
    $testContent = Get-Content -LiteralPath $testFile.FullName -Raw
    $testCount += [regex]::Matches(
        $testContent,
        '\[(TestMethod|DataRow|Fact|InlineData|Test|TestCase)\b').Count
}

$handwritten = $classificationRows |
    Where-Object classification -eq 'handwritten' |
    Select-Object -First 1
$thresholds = [ordered]@{
    projects = [ordered]@{
        actual = $projectFiles.Count
        minimum = $MinimumProjects
        passed = $projectFiles.Count -ge $MinimumProjects
    }
    handwrittenLines = [ordered]@{
        actual = $handwritten.lines
        minimum = $MinimumHandwrittenLines
        passed = $handwritten.lines -ge $MinimumHandwrittenLines
    }
    tests = [ordered]@{
        actual = $testCount
        minimum = $MinimumTests
        passed = $testCount -ge $MinimumTests
    }
}

$scorecard = [ordered]@{
    generatedAtUtc = [DateTimeOffset]::UtcNow.ToString('O')
    root = $resolvedRoot
    topology = [ordered]@{
        projects = $projectFiles.Count
        projectReferenceEdges = $projectReferenceEdges
        uniqueDirectPackages = $packageNames.Count
    }
    source = [ordered]@{
        files = $sourceFiles.Count
        lines = ($sourceMeasurements | Measure-Object -Property Lines -Sum).Sum
        axamlViews = @($sourceFiles | Where-Object Extension -eq '.axaml').Count
        classifications = $classificationRows
    }
    verification = [ordered]@{
        declaredTests = $testCount
        testProjects = @($projectFiles | Where-Object Name -like '*.Tests.csproj').Count
    }
    thresholds = $thresholds
}

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null
$jsonPath = Join-Path $OutputDirectory 'complexity-scorecard.json'
$markdownPath = Join-Path $OutputDirectory 'complexity-scorecard.md'
$scorecard | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $jsonPath -Encoding utf8

$markdown = @"
# AtlasOps complexity scorecard

Generated at $($scorecard.generatedAtUtc).

| Dimension | Value |
|---|---:|
| Projects | $($scorecard.topology.projects) |
| Project-reference edges | $($scorecard.topology.projectReferenceEdges) |
| Unique direct packages | $($scorecard.topology.uniqueDirectPackages) |
| C# and AXAML files | $($scorecard.source.files) |
| C# and AXAML lines | $($scorecard.source.lines) |
| AXAML views | $($scorecard.source.axamlViews) |
| Declared tests | $($scorecard.verification.declaredTests) |
| Test projects | $($scorecard.verification.testProjects) |

## Source classifications

| Classification | Files | Lines | Control-flow tokens |
|---|---:|---:|---:|
$(
    ($classificationRows | ForEach-Object {
        "| $($_.classification) | $($_.files) | $($_.lines) | $($_.controlFlowTokens) |"
    }) -join "`n"
)

## Thresholds

| Threshold | Actual | Minimum | Passed |
|---|---:|---:|:---:|
| Projects | $($thresholds.projects.actual) | $($thresholds.projects.minimum) | $($thresholds.projects.passed) |
| Handwritten lines | $($thresholds.handwrittenLines.actual) | $($thresholds.handwrittenLines.minimum) | $($thresholds.handwrittenLines.passed) |
| Declared tests | $($thresholds.tests.actual) | $($thresholds.tests.minimum) | $($thresholds.tests.passed) |
"@
$markdown | Set-Content -LiteralPath $markdownPath -Encoding utf8

$failedThresholds = @($thresholds.GetEnumerator() | Where-Object { -not $_.Value.passed })
if ($failedThresholds.Count -gt 0) {
    $names = $failedThresholds | ForEach-Object Key
    Write-Error "Complexity thresholds failed: $($names -join ', ')."
}

Write-Host "Wrote $jsonPath"
Write-Host "Wrote $markdownPath"
